model_name: 'tinyLPR'
# lr: 1.0e-3
lr: 3.0e-4
batch_size: &bs 128
epochs: 100
eval_freq: 5

time_steps: &ts 8
blank_id: &bi 0
num_classes: &nc 68

img_size: [32, 96]
input_shape: [32, 96, 1]
seed: 0

checkpoint_path: "backup/m_size_0.9915.pth"

# data config
train:
  maxT: *ts
  image_dir: /workspace/datasets/lpr/images/train
  data_aug: True

val:
  maxT: *ts
  image_dir: /workspace/datasets/lpr/images/val
  data_aug: False

test:
  maxT: *ts
  image_dir: /workspace/datasets/lpr/images/test
  data_aug: False
